# Generated by Django 6.0.7 on 2026-08-11 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("port", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="contact",
            name="subject",
            field=models.CharField(max_length=200),
        ),
    ]
